server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      hbm2ddl:
        auto: update
      show_sql: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  mvc:
    static-path-pattern: /static/**
